<?php

$monthlycleanupcountercats = array(
  'Accuracy disputes',
  'Articles lacking page references',
  'BLP articles lacking sources',
  'Unreferenced BLPs',
  'Category needed',
  'Articles needing chemical formulas',
  'Articles with broken or outdated citations',
  'Wikipedia articles needing clarification',
  'Wikipedia pages needing cleanup',
  'Articles needing cleanup',
  'Wikipedia articles with possible conflicts of interest',
  'Wikipedia articles needing context',
  'Wikipedia articles needing copy edit',
  'Copied and pasted articles and sections',
  'Articles containing potentially dated statements',
  'Articles with dead external links',
  'Dead-end pages',
  'Articles with disputed statements',
  'Articles to be expanded',
  'Articles needing expert attention by month',
  'Wikipedia external links cleanup',
  'Articles that need to differentiate between fact and fiction',
  'Articles sourced only by IMDB',
  'Articles sourced by IMDB',
  'Articles lacking in-text citations',
  'Wikipedia introduction cleanup',
  'Articles needing link rot cleanup',
  'Articles to be merged',
  'Articles with topics of unclear notability',
  'NPOV disputes',
  'Articles that may contain original research',
  'Orphaned articles',
  'Articles with minor POV problems',
  'Wikipedia articles needing page number citations',
  'Articles with peacock terms',
  'Wikipedia articles with plot summary needing attention',
  'Articles with a promotional tone',
  'Articles with sections that need to be turned into prose',
  'Articles to be pruned',
  'Articles slanted towards recent events',
  'Recently revised',
  'Articles needing additional references',
  'Articles lacking reliable references',
  'Wikipedia articles needing rewrite',
  'Articles needing sections',
  'Articles with excessive "see also" sections',
  'Self-contradictory articles',
  'Articles lacking sources',
  'Wikipedia spam cleanup',
  'Articles to be split',
  'Article sections to be split',
  'Articles that may be too long',
  'Wikipedia articles needing style editing',
  'Wikipedia articles that are too technical',
  'Articles with trivia sections',
  'Uncategorized stubs',
  'Unreviewed new articles',
  'Unreviewed new articles created via the Article Wizard',
  'Articles with unsourced statements',
  'Wikipedia articles in need of updating',
  'Wikipedia articles needing factual verification',
  'Articles with weasel words',
  'Articles with specifically marked weasel-worded phrases',
  'Articles needing the year an event occurred',
  'Articles with obsolete information',
  'Wikipedia articles needing reorganization',
  'Cleanup section',
  'Articles with close paraphrasing of public domain sources',
  'Wikipedia list cleanup',
  'Articles needing more viewpoints',
  'Articles requiring tables',
  'Articles with limited geographic scope',
  'Wikipedia laundry list cleanup',
  'Wikipedia references cleanup',
  'Vague or ambiguous time',
  'Articles with improper non-free content (lists)',
  '1911 Britannica articles needing updates',
  'Incomplete lists',
  'Articles with improper non-free content',
  'Disambiguation pages in need of cleanup',
  'Articles about possible neologisms',
  'Incomplete disambiguation',
  'Articles with links needing disambiguation',
  'Articles with disproportional geographic scope',
  'Wikipedia articles containing buzzwords',
  'Vague or ambiguous geographic scope',
  'Suspected copyright infringements without a source',
  'Pages with excessive dablinks',
  'Wikipedia articles without plot summaries',
  'Wikipedia red link cleanup',
  'Autobiographical articles',
  'NRHP articles with dead external links',
  'Copied and pasted articles and sections with url provided',
  'Articles to be expanded with sources',
  'Articles with close paraphrasing',
  'Articles with too few wikilinks');
$cleanupcountercats = array(
  'Tree of Life cleanup',
  'Animals cleanup',
  'Invalid conservation status',
  'Missing taxobox',
  'Plant articles needing a taxobox',
  'Redundant taxobox',
  'Taxoboxes needing a status system parameter',
  'Taxoboxes with an invalid color',
  'Taxoboxes with an unrecognised status system',
  'All articles needing coordinates',
  'Proposed moves',
  'Pages with DOIs inactive since 2008',
  'Pages with DOIs inactive since 2009',
  'Pages with DOIs inactive since 2010',
  'Pages with DOIs inactive since 2011',
  'All articles needing expert attention',
  'Persondata templates without short description parameter',
  'Pages with several capitalization mistakes');
$classes = array("FA", "A", "GA", "Bplus", "B", "C", "Start", "Stub", "FL", "List", "Unassessed", "NA", "Book", "Category", "Current", "Disambig", "File", "Future", "Merge", "Needed", "Portal", "Project", "Redirect", "Template");
$importances = array("Top", "High", "Mid", "Low", "Unknown", "NA", "Bottom", "No");

?>
